#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

name: Python package

on:
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ts-graphviz/setup-graphviz@v1
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_tools/requirements/envs/pytest.env.txt
          pip install --no-deps -e .
      - run: |
          check/pytest

  pytest-dev-tools:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ts-graphviz/setup-graphviz@v1
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_tools/requirements/envs/dev.env.txt
          pip install --no-deps -e .
      - run: |
          check/pytest-dev-tools

  notebooks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ts-graphviz/setup-graphviz@v1
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_tools/requirements/envs/pytest.env.txt
          pip install --no-deps -e .
      - run: |
          python dev_tools/execute-notebooks.py

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_tools/requirements/envs/format.env.txt
          pip install --no-deps -e .
      - run: |
          check/format-incremental

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev_tools/requirements/envs/pylint.env.txt
          pip install --no-deps -e .
      - run: |
          check/pylint
